### ISSUE TITLE
Lab study AY 20/21

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/examples_open_science#4]
- [Bustin et al 2020](https://benjamins.com/catalog/ihll.26.01bra)
- Marasco (initial cues abstract)
- Marasco (secondary cues abstract)

**Comment by nmrodriguez** [comment]
I found a few dissertations that could be helpful for references
-  [L2 Spanish Intonation - 6 week SA context ](https://fsu.digital.flvc.org/islandora/object/fsu%3A253221/datastream/PDF/view)
- [L2 Spanish Intonation - SA context ](https://conservancy.umn.edu/bitstream/handle/11299/175354/Trimble_umn_0130E_13962.pdf;sequence=1)

**Comment by kparrish92** [comment]
Here is the chapter that Juanjo mentioned: 

[Brandl, Gonzalez & Bustin_2020_The development of intonation in Spanish.pdf](https://github.com/RAP-group/examples_open_science/files/5252696/Brandl.Gonzalez.Bustin_2020_The.development.of.intonation.in.Spanish.pdf)

**Comment by laurafdeza** [comment]
[Santiago & Delais-Roussarie, 2015](https://link.springer.com/chapter/10.1007/978-3-662-45168-7_12)

[Zárate-Sández, 2015](https://repository.library.georgetown.edu/handle/10822/761510) (dissertation)

[Kim, 2016](http://hdl.handle.net/2142/92717) (dissertation)

Then I also found a bunch on training and with other languages. Do we want those too?

**Comment by kparrish92** [comment]
I think they could be relevant if we are aiming to examine ultimate attainment in L2 prosody in general/any L2 (although I know we haven't yet asked a particular research question). We could also examine training's role in ultimate attainment (or whether it makes a difference). So we can either focus on training or ultimate attainment, using one as an explanation for the other.  If we decide we are not interested in training, then we could focus on something like ultimate attainment (it would be useful to know whether native-like L2 prosody has been found in distinct L2's)

**Comment by RobertEspo** [comment]
Hi guys. I found two perception studies from Professor d'Imperio that might be interesting. [This one](https://idp.springer.com/authorize/casa?redirect_uri=https://link.springer.com/content/pdf/10.3758/s13421-019-00990-w.pdf&casa_token=TL2bIQxknHwAAAAA:EdOoBkYYWmgoL6VJSpsdPlm2sUTjl86ToExBA_L4tHD3iFRIB7Sy3bRSDMaWbY6sc46O0GfxE8RvcC7X) is examining empathy's role to disambiguate lexical meaning through intonation. They found that lower empathy individuals did not disambiguate immediately, whereas higher empathy individuals formed distinct meanings.

[In this one](http://www.assta.org/proceedings/ICPhS2019/papers/ICPhS_2995.pdf), participants had to judge recordings based on "perceived speaker certainty." They found that native speakers of an Italian variety rated speakers of the same variety as more uncertain if the listener had more experience with speakers of other varieties of Italian.
 
Maybe examining empathy's interaction with intonation in L2 Spanish speakers would be interesting. The second study could motivate us to keep track of "how many varieties" L2ers are exposed to (I'm not sure how we would accurately elicit this; number of teachers? television shows watched? music listened to?).

**Comment by jvcasillas** [comment]
Overview of Spanish resyllabification idea

- Spanish has resyllabification processes
	- word-final consonants are resyllabified with the initial vowel of a following word  
	"el amigo" e.la.mi.go
- It's been proposed that consonant duration could be a perceptual cue to identify consonants as word-final or word-initial in ambiguous contexts

```
nos huelen vs. no  suelen  /no.ˈsue.len/  
eras ancho vs. era Sancho  /ˈe.ɾa.ˈsaN.tʃo/

Dice que nos huelen venir de lejos
Dice que no suelen venir de lejos

Dijo que eras ancho. 
Dijo que era Sancho.
```

- If true, native Spanish speakers must process fine-grained duration differences during speech perception
- L2 learners must learn to pay attention to durational cues to efficiently parse L2 speech

**Comment by kparrish92** [comment]
Overview of the role of empathy on second language acquisition of intonation

L1 speakers of French with higher empathy disambiguated sentences more easily than lower empathy speakers. (Esteve-Gibert et al., 2020). Higher empathy showed a higher degree of sensitivity to tonal differences. 
In L2 Spanish, as proficiency increases, so does the ability to distinguish questions from statements based on intonational differences (Brandl et al., 2020)
Empathy was measured by a self reported Empathy Quotient (EQ) questionnaire was used to measure empathy (Baron-Cohen & Wheelwright, 2004). Including this study, which has the questionnaire included at the end. Looks like it could be programmed into psychopy. 

Proposed research question:

Do L2 learners of Spanish with higher empathy acquire tonal information either more quickly or at lower levels of proficiency compared to lower empathy L2 learners?

Methods: 

We would need to come up with a methodology that is distinct from Esteve-Gibert et al. (The study that Robert mentioned), since that was a visual world eye-tracking study. We could try and come up with some sort of forced choice task after hearing stimuli. 

The Brandl et al. study (Amy’s co-authored study) used an intonation matching task, where they had to choose whether a sentence they heard and saw matched one another. 

Justifications:

This study could contribute to the overall idea that individual differences play a role in language acquisition and language processing by adding pragmatic skills to the equation. We can expand findings from native languages to second languages also, to inform debates on possible ultimate attainment of a second language.  



Baron-Cohen, S., & Wheelwright, S. (2004). The empathy quotient: An investigation of adults with Asperger syndrome or high functioning autism, and normal sex differences. Journal of Autism and Developmental Disorders, 34(2), 163–175.
PDF:
[BaronCohen&Wheelwright2004.pdf](https://github.com/RAP-group/examples_open_science/files/5285385/BaronCohen.Wheelwright2004.pdf)


Esteve-Gibert, N., Schafer, A., Hemforth, B., Portes, C., Pozniak, C., & D’Imperio, M. (2020). Empathy influences how listeners interpret intonation and meaning when words are ambiguous. Memory & Cognition, 48(4), 566–580. https://doi.org/10.3758/s13421-019-00990-w
PDF:
[Esteve-Gibert2020_Article_EmpathyInfluencesHowListenersI (1).pdf](https://github.com/RAP-group/examples_open_science/files/5285386/Esteve-Gibert2020_Article_EmpathyInfluencesHowListenersI.1.pdf)

[Brandl.Gonzalez.Bustin_2020_The.development.of.intonation.in.Spanish (2).pdf](https://github.com/RAP-group/examples_open_science/files/5285382/Brandl.Gonzalez.Bustin_2020_The.development.of.intonation.in.Spanish.2.pdf)

**Comment by jvcasillas** [comment]
Thanks @kparrish92. Perfect. @obliviscere take a look at this.

**Comment by RobertEspo** [comment]
I'm wondering if the sentence "que quiere comer" might be useful for a forced-choice task or other sentences like that? It can have three interpretations (statement, yes-no q, and wh-q). They listen to the sentence, we give them possible responses and they have to choose the most fitting response.

"Que quiere comer(?)"
A. [wh-question response] Mandarinas.
B. [yes-no question response] Si.
C. [statement response; I'm reading it as "ya te he dicho que quiere comer!"] Ay, perdon, si, ya me dijiste.

That last one, I'm not sure how clear it is... but if the Brandl et all study already did something on declaratives vs questions, maybe we can look into specifically questions more and tease about wh- vs yes-no questions?

This unfortunately doesn't really seem to inform about the empathy stuff. Maybe high-empathy individuals will be more geared towards teasing apart the differences at a lower proficiency level?

---

I think that the resyllabification idea sounds cool. I found this study: https://eresearch.qmu.ac.uk/bitstream/handle/20.500.12289/4322/eResearch%25204322.pdf?sequence=1&isAllowed=y. They did a read-aloud task of the form "ahora digo [word]". It specifically focuses on /s/ in Iberian Spanish. They found that resyllabified /s/ is longer than coda /s/, BUT not longer than medial or initial /s/.

Here's a dissertation I found published in 2017: https://www.ideals.illinois.edu/handle/2142/97243. They have production and perception tasks. In the abstract, they talk about a mismatch in production/perception that is unexpected based on previous research ("complete resyllabification" Harris 1983).

See y'all next week :)

**Comment by jvcasillas** [comment]
> I'm wondering if the sentence "que quiere comer" might be useful for a forced-choice task or other sentences like that? It can have three interpretations (statement, yes-no q, and wh-q). They listen to the sentence, we give them possible responses and they have to choose the most fitting response.
> 
> "Que quiere comer(?)"
> A. [wh-question response] Mandarinas.
> B. [yes-no question response] Si.
> C. [statement response; I'm reading it as "ya te he dicho que quiere comer!"] Ay, perdon, si, ya me dijiste.
> 
> That last one, I'm not sure how clear it is... but if the Brandl et all study already did something on declaratives vs questions, maybe we can look into specifically questions more and tease about wh- vs yes-no questions?
> 

I like this idea. I think ideally we would do a direct replication of the Brandl et al study and we could add in what you suggest (in another testing block) to expand on what they did. 


> This unfortunately doesn't really seem to inform about the empathy stuff. Maybe high-empathy individuals will be more geared towards teasing apart the differences at a lower proficiency level?
> 

This would be the hypothesis. So if we conceive of proficiency as a continuous variable we would expect a proficiency x empathy interaction in which higher empathy is associated with earlier learning. This is rather interesting and novel from an SLA perspective. 

> I think that the resyllabification idea sounds cool. I found this study: https://eresearch.qmu.ac.uk/bitstream/handle/20.500.12289/4322/eResearch%25204322.pdf?sequence=1&isAllowed=y. They did a read-aloud task of the form "ahora digo [word]". It specifically focuses on /s/ in Iberian Spanish. They found that resyllabified /s/ is longer than coda /s/, BUT not longer than medial or initial /s/.
> 
> Here's a dissertation I found published in 2017: https://www.ideals.illinois.edu/handle/2142/97243. They have production and perception tasks. In the abstract, they talk about a mismatch in production/perception that is unexpected based on previous research ("complete resyllabification" Harris 1983).
> 

These are both key articles. The Scarpace dissertation is really the only study I've ever seen that looked at this in recent years (and he used eye tracking). We will keep this idea on the back burner. 


> See y'all next week :)

**Comment by laurafdeza** [comment]
What do you all think about something involving gating? Trimble (2013, pp. 83-84) used it in case we want to use it as "model."
[trimble_2013.pdf](https://github.com/RAP-group/examples_open_science/files/5301389/trimble_2013.pdf)

**Comment by jvcasillas** [comment]
> What do you all think about something involving gating? Trimble (2013, pp. 83-84) used it in case we want to use it as "model."
> [trimble_2013.pdf](https://github.com/RAP-group/examples_open_science/files/5301389/trimble_2013.pdf)

I haven't read the study, but I like this idea. My main concern with the methodology from the Bustin study is that it might be too easy. A gating paradigm might reveal more fine grained differences as a function of proficiency (and empathy). I'm going to think about this a bit more.

**Comment by jvcasillas** [comment]
Closing this issue. We can now talk about project in dedicated repo.
